### ISSUE TITLE
fisherABM: Reproduction Function 

### ISSUE THREAD

**Issue by TylerMuhly** [bcgov/castor#338]
Function for producing female fisher kits from reproductively mature fisher. 

![fisher_abm_reproduce](https://user-images.githubusercontent.com/34694298/180839721-e6fdf676-9e3d-4a4d-bd9d-1f2a5bb20538.jpg)

SELECT individual_id WHERE sex = F AND age >= reproductive_age;

- rnorm (nrows(), denning_rate_mean, denning _rate_sd) AS denning_rate; _assign a denning rate to each individual_
- rbinom (1, 1, denning_rate) AS ‘kits’; _assign whether the individual has kits(1) or not(0) from a binomial draw of denning_rate_
- IF kits = 0, remove from table

ELSE 
- kits = rnorm (nrows(), litter_size_mean, litter_size_sd); _assign a litter size based on distribution_

FOR EACH individual_id create a data.table with agent table columns and nrows (kits)
- ASSIGN to kits:
- individual id = seq (from = max (agents::individual_id), to = (max (agents::individual_id) + 1, by = 1) 
    - age = 0
    - location = SELECT pixelid FROM agents WHERE individual_id = individual_id
    - hr_size = rnorm (1, female_hr_size_mean, female_hr_size_sd)
    - sex = rbinom (1, 1, sex_ratio) IF 1 = “F” ELSE = “M”
    - rbind() to “agents” table
- IF sex = “M” remove from table

**Parameters:**
- reproductive_age: age that a female reaches sexual maturity
- denning_rate_mean: Mean rate or proportion of females that den and give birth to kits
- denning_rate_sd: standard deviation of rate or proportion of females that den and give birth to kits
- litter_size_mean: Mean number of kits born in a litter
- litter_size_sd: standard deviation of the number of kits born in a litter
- female_hr_size_mean = average home range size, ha
- female_hr_size_sd = standard deviation of home range size, ha

**Comment by TylerMuhly** [comment]
Reproduction rates could be adjusted by habitat quality (d2 score).

**Comment by joburgar** [comment]
Completed Aug 9 - but will need to work with team to make sure it's SpaDES friendly. Also added in Fisher Habitat Zone parameter (will take from each individual's pixelID and associated Fisher Habitat Extension Zone value) to get proper D2 values per habitat zone type. Also added in function to find CIs for denning rate to use rbinom rather than rnorm. Litter size was influenced by habitat quality. Will need to check with fisher team if values seem probable (reduce litter size by 1/4 if d2 > mean, reduce litter size by 1/2 if d2 > mean +SD, and have no kits if d2 > max).
